"""alert events

Revision ID: b81e22be8ed4
Revises: 8e407b723127
Create Date: 2026-09-23 10:42:49.207374

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b81e22be8ed4'
down_revision: str | Sequence[str] | None = '8e407b723127'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('alertname', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generator_url', sa.String(length=1024), nullable=True),
    sa.Column('first_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receive_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'fingerprint', 'starts_at', name='uq_alert_event_identity')
    )
    op.create_index(op.f('ix_alert_events_alertname'), 'alert_events', ['alertname'], unique=False)
    op.create_index('ix_alert_events_cluster_status', 'alert_events', ['cluster_id', 'status'], unique=False)
    op.create_index(op.f('ix_alert_events_fingerprint'), 'alert_events', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_alert_events_namespace'), 'alert_events', ['namespace'], unique=False)
    op.create_index(op.f('ix_alert_events_severity'), 'alert_events', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_events_starts_at'), 'alert_events', ['starts_at'], unique=False)
    op.create_index('ix_alert_events_team_status', 'alert_events', ['team_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_team_status', table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_starts_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_severity'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_namespace'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_fingerprint'), table_name='alert_events')
    op.drop_index('ix_alert_events_cluster_status', table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alertname'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
